package features;

import java.util.Scanner;

// This is the main entry point for the Inverted Index feature.
// It builds the index from the CSV file and allows the user to search for words.
public class InvertedIndexMain {

    public static void main(String[] args) {

        // Create the inverted index object
        InvertedIndex phoneIndex = new InvertedIndex();

        // Path to the CSV file generated by the crawler
        String csvPath = "src/main/resources/Combined_phone.csv";

        // Build the index by reading the CSV file
        System.out.println("Building the inverted index...");
        phoneIndex.buildIndex(csvPath);

        // Setup scanner to read user input
        Scanner scanner = new Scanner(System.in);
        String query;

        System.out.println("\n========================================");
        System.out.println("   Smartphone Inverted Index Search");
        System.out.println("   Type 'exit' to quit");
        System.out.println("========================================");

        // Keep asking user for search words until they type 'exit'
        while (true) {
            System.out.print("\nEnter a word to search: ");
            query = scanner.nextLine().trim();

            // Check if user entered an empty query
            if (query.isEmpty()) {
                System.out.println("Please enter a word.");
                continue;
            }

            // Check if user wants to exit
            if (query.equalsIgnoreCase("exit")) {
                System.out.println("Goodbye!");
                break;
            }

            // Search and display results
            phoneIndex.search(query);
        }

        scanner.close();
    }
}